model:
  target: ldm.modules.diffusionmodules.maskmodel.MaskUNetModel
  params:
    image_size: 64 # unused
    in_channels: 4
    out_channels: 1
    model_channels: 160
    attention_resolutions: [] #[ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_heads: 8
    use_spatial_transformer: True
    transformer_depth: 1
    context_dim: 768
    use_checkpoint: True
    legacy: False

cond_stage_config:
  target: ldm.modules.encoders.modules.FrozenCLIPEmbedder


trainset:
  target: mask_est.fashiongen.dataset.MaskTrain
  params:
    size: 128

validset:
  target: mask_est.fashiongen.dataset.MaskValid
  params:
    size: 128
